package org.accretegb.modules.hibernate;
// Generated Jan 7, 2016 12:35:46 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Classification generated by hbm2java
 */
@Entity
@Table(name = "classification", catalog = "agbv2")
public class Classification implements java.io.Serializable {

	private Integer classificationId;
	private String classification_code;
	private String classification_type;
	private Set<Passport> passports = new HashSet(0);

	public Classification() {
	}

	public Classification( String classification_code, String classification_type, Set<Passport> passports) {
		this.classification_code = classification_code;
		this.classification_type = classification_type;
		this.passports = passports;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "classification_id", unique = true, nullable = false)
	public Integer getClassificationId() {
		return this.classificationId;
	}

	public void setClassificationId(Integer classificationId) {
		this.classificationId = classificationId;
	}

	@Column(name = "classification_code")
	public String getClassificationCode() {
		return this.classification_code;
	}

	public void setClassificationCode(String classification_code) {
		this.classification_code = classification_code;
	}

	@Column(name = "classification_type")
	public String getClassificationType() {
		return this.classification_type;
	}

	public void setClassificationType(String classification_type) {
		this.classification_type = classification_type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classification")
	public Set<Passport> getPassports() {
		return this.passports;
	}

	public void setPassports(Set<Passport> passports) {
		this.passports = passports;
	}

}
