package org.accretegb.modules.hibernate;

// default package
// Generated May 27, 2015 9:54:40 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CollaborateRelation generated by hbm2java
 */
@Entity
@Table(name = "collaborate_relation")
public class CollaborateRelation implements java.io.Serializable {

	private Integer collaborateRelationId;
	private int projectId;
	private int userId;

	public CollaborateRelation() {
	}

	public CollaborateRelation(int projectId, int userId) {
		this.projectId = projectId;
		this.userId = userId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "collaborate_relation_id", unique = true, nullable = false)
	public Integer getCollaborateRelationId() {
		return this.collaborateRelationId;
	}

	public void setCollaborateRelationId(Integer collaborateRelationId) {
		this.collaborateRelationId = collaborateRelationId;
	}

	@Column(name = "project_id", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

}
