package org.accretegb.modules.hibernate;
// Generated Jan 7, 2016 12:35:46 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ContainerLocation generated by hbm2java
 */
@Entity
@Table(name = "container_location", catalog = "agbv2")
public class ContainerLocation implements java.io.Serializable {

	private Integer container_location_id;
	private Location location;
	private String building;
	private String room;
	private String containerLocationComments;
	private String tier1_position;
	private String tier2_position;
	private String tier3_position;
	private String shelf;
	private Set<StockPacketContainer> stockPacketContainers = new HashSet(0);

	public ContainerLocation() {
	}

	public ContainerLocation(Location location, String building, String room,
		 String tier1_position, String tier2_position, String tier3_position, String shelf, String containerLocationComments, Set<StockPacketContainer> stockPacketContainers) {
		this.location = location;
		this.building = building;
		this.room = room;
		this.containerLocationComments = containerLocationComments;
		this.tier1_position = tier1_position;
		this.tier2_position = tier2_position;
		this.tier3_position = tier3_position;
		this.shelf = shelf;
		this.stockPacketContainers = stockPacketContainers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "container_location_id", unique = true, nullable = false)
	public Integer getContainerLocationId() {
		return this.container_location_id;
	}

	public void setContainerLocationId(Integer containerLocationId) {
		this.container_location_id = containerLocationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "location_id",nullable = false)
	public Location getLocation() {
		return this.location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

	@Column(name = "building")
	public String getBuilding() {
		return this.building;
	}

	public void setBuilding(String building) {
		this.building = building;
	}

	@Column(name = "room")
	public String getRoom() {
		return this.room;
	}

	public void setRoom(String room) {
		this.room = room;
	}

	@Column(name = "container_location_comments", length = 65535)
	public String getContainerLocationComments() {
		return this.containerLocationComments;
	}

	public void setContainerLocationComments(String containerLocationComments) {
		this.containerLocationComments = containerLocationComments;
	}

	@Column(name = "tier1_position", length = 45)
	public String getTier1() {
		return this.tier1_position;
	}

	public void setTier1(String tier1_position) {
		this.tier1_position = tier1_position;
	}

	@Column(name = "tier2_position", length = 45)
	public String getTier2() {
		return this.tier2_position;
	}

	public void setTier2(String tier2_position) {
		this.tier2_position = tier2_position;
	}

	@Column(name = "tier3_position", length = 45)
	public String getTier3() {
		return this.tier3_position;
	}

	public void setTier3(String tier3_position) {
		this.tier3_position = tier3_position;
	}

	@Column(name = "shelf", length = 45)
	public String getShelf() {
		return this.shelf;
	}

	public void setShelf(String shelf) {
		this.shelf = shelf;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "containerLocation")
	public Set<StockPacketContainer> getStockPacketContainers() {
		return this.stockPacketContainers;
	}

	public void setStockPacketContainers(Set<StockPacketContainer> stockPacketContainers) {
		this.stockPacketContainers = stockPacketContainers;
	}

}
