package org.accretegb.modules.hibernate;
// Generated Jan 7, 2016 12:35:46 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ExperimentFactor generated by hbm2java
 */
@Entity
@Table(name = "experiment_factor", catalog = "agbv2" )
public class ExperimentFactor implements java.io.Serializable {

	private Integer experimentFactorId;
	private String expFactorName;
	private String expFactorType;
	private String expFactorDesc;
	private String expFactorComments;
	private Set<ExperimentFactorValue> experimentFactorValues = new HashSet(0);

	public ExperimentFactor() {
	}

	public ExperimentFactor( String expFactorName, String expFactorType,
			String expFactorDesc,String expFactorComments, Set<ExperimentFactorValue> experimentFactorValues) {
		this.expFactorName = expFactorName;
		this.expFactorType = expFactorType;
		this.expFactorDesc = expFactorDesc;
		this.expFactorComments = expFactorComments;
		this.experimentFactorValues = experimentFactorValues;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "experiment_factor_id", unique = true, nullable = false)
	public Integer getExperimentFactorId() {
		return this.experimentFactorId;
	}

	public void setExperimentFactorId(Integer experimentFactorId) {
		this.experimentFactorId = experimentFactorId;
	}

	@Column(name = "exp_factor_name")
	public String getExpFactorName() {
		return this.expFactorName;
	}

	public void setExpFactorName(String expFactorName) {
		this.expFactorName = expFactorName;
	}

	@Column(name = "exp_factor_type")
	public String getExpFactorType() {
		return this.expFactorType;
	}

	public void setExpFactorType(String expFactorType) {
		this.expFactorType = expFactorType;
	}

	@Column(name = "exp_factor_desc")
	public String getExpFactorDesc() {
		return this.expFactorDesc;
	}

	public void setExpFactorDesc(String expFactorDesc) {
		this.expFactorDesc = expFactorDesc;
	}

	@Column(name = "exp_factor_comments", length = 65535)
	public String getExpFactorComments() {
		return this.expFactorComments;
	}

	public void setExpFactorComments(String expFactorComments) {
		this.expFactorComments = expFactorComments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "experimentFactor")
	public Set<ExperimentFactorValue> getExperimentFactorValues() {
		return this.experimentFactorValues;
	}

	public void setExperimentFactorValues(Set<ExperimentFactorValue> experimentFactorValues) {
		this.experimentFactorValues = experimentFactorValues;
	}

}
