package org.accretegb.modules.hibernate;

// default package
// Generated Jun 15, 2015 2:18:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * experimentGroup generated by hbm2java
 */
@Entity
@Table(name = "experiment_group")
public class ExperimentGroup implements java.io.Serializable {

	private Integer experimentGroupId;
	private int projectId;
	private String experimentGroupName;
	private String stockListJson;
	private String ExpResultJson;

	public ExperimentGroup() {
	}

	public ExperimentGroup(int projectId, String experimentGroupName,
			String stockListJson, String ExpResultJson) {
		this.projectId = projectId;
		this.experimentGroupName = experimentGroupName;
		this.stockListJson = stockListJson;
		this.ExpResultJson = ExpResultJson;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "experiment_group_id", unique = true, nullable = false)
	public Integer getexperimentGroupId() {
		return this.experimentGroupId;
	}

	public void setexperimentGroupId(Integer experimentGroupId) {
		this.experimentGroupId = experimentGroupId;
	}

	@Column(name = "project_id", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "experiment_group_name", nullable = false, length = 45)
	public String getExperimentGroupName() {
		return this.experimentGroupName;
	}

	public void setExperimentGroupName(String experimentGroupName) {
		this.experimentGroupName = experimentGroupName;
	}

	@Column(name = "stockList_json", nullable = true)
	public String getStockListJson() {
		return this.stockListJson;
	}

	public void setStockListJson(String stockListJson) {
		this.stockListJson = stockListJson;
	}

	@Column(name = "expResult_json", nullable = true)
	public String getExpResultJson() {
		return this.ExpResultJson;
	}

	public void setExpResultJson(String ExpResultJson) {
		this.ExpResultJson = ExpResultJson;
	}

}
