package org.accretegb.modules.hibernate;

// default package
// Generated Jun 15, 2015 2:18:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HarvestingGroup generated by hbm2java
 */
@Entity
@Table(name = "harvesting_group")
public class HarvestingGroup implements java.io.Serializable {

	private Integer harvestingGroupId;
	private int projectId;
	private String harvestingGroupName;
	private String crossRecordJson;
	private String bulkJson;
	private String stickerGeneratorJson;

	public HarvestingGroup() {
	}

	public HarvestingGroup(int projectId, String harvestingGroupName,
			String crossRecordJson, String bulkJson, String stickerGeneratorJson) {
		this.projectId = projectId;
		this.harvestingGroupName = harvestingGroupName;
		this.crossRecordJson = crossRecordJson;
		this.bulkJson = bulkJson;
		this.stickerGeneratorJson = stickerGeneratorJson;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "harvesting_group_id", unique = true, nullable = false)
	public Integer getHarvestingGroupId() {
		return this.harvestingGroupId;
	}

	public void setHarvestingGroupId(Integer harvestingGroupId) {
		this.harvestingGroupId = harvestingGroupId;
	}

	@Column(name = "project_id", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "harvesting_group_name", nullable = false, length = 45)
	public String getHarvestingGroupName() {
		return this.harvestingGroupName;
	}

	public void setHarvestingGroupName(String harvestingGroupName) {
		this.harvestingGroupName = harvestingGroupName;
	}

	@Column(name = "crossRecord_json", nullable = true)
	public String getCrossRecordJson() {
		return this.crossRecordJson;
	}

	public void setCrossRecordJson(String crossRecordJson) {
		this.crossRecordJson = crossRecordJson;
	}

	@Column(name = "bulk_json", nullable = true)
	public String getBulkJson() {
		return this.bulkJson;
	}

	public void setBulkJson(String bulkJson) {
		this.bulkJson = bulkJson;
	}

	@Column(name = "stickerGenerator_json", nullable = true)
	public String getStickerGeneratorJson() {
		return this.stickerGeneratorJson;
	}

	public void setStickerGeneratorJson(String stickerGeneratorJson) {
		this.stickerGeneratorJson = stickerGeneratorJson;
	}

}
