package org.accretegb.modules.hibernate;
// Generated Jan 7, 2016 12:35:46 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Mate generated by hbm2java
 */
@Entity
@Table(name = "mate", catalog = "agbv2")
public class Mate implements java.io.Serializable {

	private Integer MateId;
	private String matingType;
	private String mateRole;
	private Set<MateMethodConnect> mateMethodConnects = new HashSet(0);

	public Mate() {
	}

	public Mate(String matingType, String mateRole, Set<MateMethodConnect> mateMethodConnects) {
		this.matingType = matingType;
		this.mateRole = mateRole;
		this.mateMethodConnects = mateMethodConnects;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "mate_id", unique = true, nullable = false)
	public Integer getMateId() {
		return this.MateId;
	}

	public void setMateId(Integer MateId) {
		this.MateId = MateId;
	}

	@Column(name = "mating_type")
	public String getMatingType() {
		return this.matingType;
	}

	public void setMatingType(String matingType) {
		this.matingType = matingType;
	}

	@Column(name = "mate_role",nullable = false)
	public String getMateRole() {
		return this.mateRole;
	}

	public void setMateRole(String mateRole) {
		this.mateRole = mateRole;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mate")
	public Set<MateMethodConnect> getMateMethodConnects() {
		return this.mateMethodConnects;
	}

	public void setMateMethodConnects(Set<MateMethodConnect> mateMethodConnects) {
		this.mateMethodConnects = mateMethodConnects;
	}

}
