package org.accretegb.modules.hibernate;
// Generated Jan 7, 2016 12:35:46 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MeasurementType generated by hbm2java
 */
@Entity
@Table(name = "measurement_type", catalog = "agbv2")
public class MeasurementType implements java.io.Serializable {

	private Integer measurementTypeId;
	private String measurementType;
	private Set<MeasurementValue> measurementValues = new HashSet(0);

	public MeasurementType() {
	}

	public MeasurementType(String measurementType, Set<MeasurementValue> measurementValues) {
		this.measurementType = measurementType;
		this.measurementValues = measurementValues;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "measurement_type_id", unique = true, nullable = false)
	public Integer getMeasurementTypeId() {
		return this.measurementTypeId;
	}

	public void setMeasurementTypeId(Integer measurementTypeId) {
		this.measurementTypeId = measurementTypeId;
	}

	@Column(name = "measurement_type",nullable = false)
	public String getMeasurementType() {
		return this.measurementType;
	}

	public void setMeasurementType(String measurementType) {
		this.measurementType = measurementType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "measurementType")
	public Set<MeasurementValue> getMeasurementValues() {
		return this.measurementValues;
	}

	public void setMeasurementValues(Set<MeasurementValue> measurementValues) {
		this.measurementValues = measurementValues;
	}

}
