package org.accretegb.modules.hibernate;
// Generated Jan 13, 2016 11:31:04 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ObervationUnitSample generated by hbm2java
 */
@Entity
@Table(name = "obervation_unit_sample", catalog = "agbv2")
public class ObservationUnitSample implements java.io.Serializable {

	private Integer observationUnitSampleId;
	private ObservationUnit observationUnit;
	private Source source;
	private Date sampleDate;
	private String sampleName;
	private String observationUnitSampleComments;

	public ObservationUnitSample() {
	}

	public ObservationUnitSample(ObservationUnit observationUnit, Source source, Date sampleDate, String sampleName,
			String observationUnitSampleComments) {
		this.observationUnit = observationUnit;
		this.source = source;
		this.sampleDate = sampleDate;
		this.sampleName = sampleName;
		this.observationUnitSampleComments = observationUnitSampleComments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "observation_unit_sample_id", unique = true, nullable = false)
	public Integer getObservationUnitSampleId() {
		return this.observationUnitSampleId;
	}

	public void setObservationUnitSampleId(Integer observationUnitSampleId) {
		this.observationUnitSampleId = observationUnitSampleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "observation_unit_id", nullable = false)
	public ObservationUnit getObservationUnit() {
		return this.observationUnit;
	}

	public void setObservationUnit(ObservationUnit observationUnit) {
		this.observationUnit = observationUnit;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "source_id")
	public Source getSource() {
		return this.source;
	}

	public void setSource(Source source) {
		this.source = source;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "sample_date", length = 0, nullable = false)
	public Date getSampleDate() {
		return this.sampleDate;
	}

	public void setSampleDate(Date sampleDate) {
		this.sampleDate = sampleDate;
	}

	@Column(name = "sample_name", nullable = false)
	public String getSampleName() {
		return this.sampleName;
	}

	public void setSampleName(String sampleName) {
		this.sampleName = sampleName;
	}

	@Column(name = "observation_unit_sample_comments", length = 65535)
	public String getObservationUnitSampleComments() {
		return this.observationUnitSampleComments;
	}

	public void setObservationUnitSampleComments(String observationUnitSampleComments) {
		this.observationUnitSampleComments = observationUnitSampleComments;
	}

}
