package org.accretegb.modules.hibernate;
// Generated Jan 7, 2016 12:35:46 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Synonym generated by hbm2java
 */
@Entity
@Table(name = "passport_synonym", catalog = "agbv2")
public class PassportSynonym implements java.io.Serializable {

	private Integer passportPassportSynonymId;
	private Passport passport;
	private String synonym;
	private String synonymComments;

	public PassportSynonym() {
	}

	public PassportSynonym(Passport passport, String synonym, String synonymComments) {
		this.passport = passport;
		this.synonym = synonym;
		this.synonymComments = synonymComments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "passport_synonym_id", unique = true, nullable = false)
	public Integer getPassportSynonymId() {
		return this.passportPassportSynonymId;
	}

	public void setPassportSynonymId(Integer passportPassportSynonymId) {
		this.passportPassportSynonymId = passportPassportSynonymId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "passport_id",nullable = false)
	public Passport getPassport() {
		return this.passport;
	}

	public void setPassport(Passport passport) {
		this.passport = passport;
	}


	@Column(name = "synonym",nullable = false)
	public String getSynonym() {
		return this.synonym;
	}

	public void setSynonym(String synonym) {
		this.synonym = synonym;
	}

	@Column(name = "synonym_comments", length = 65535)
	public String getSynonymComments() {
		return this.synonymComments;
	}

	public void setSynonymComments(String synonymComments) {
		this.synonymComments = synonymComments;
	}

}
