package org.accretegb.modules.hibernate;
// Generated Jan 8, 2016 7:42:44 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PassportSet generated by hbm2java
 */
@Entity
@Table(name = "passport_set", catalog = "agbv2")
public class PassportSet implements java.io.Serializable {

	private Integer passportSetId;
	private Passport passport;
	private PassportGroup passportGroup;

	public PassportSet() {
	}

	public PassportSet(Passport passport, PassportGroup passportGroup) {
		this.passport = passport;
		this.passportGroup = passportGroup;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "passport_set_id", unique = true, nullable = false)
	public Integer getPassportSetId() {
		return this.passportSetId;
	}

	public void setPassportSetId(Integer passportSetId) {
		this.passportSetId = passportSetId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "passport_id",nullable = false)
	public Passport getPassport() {
		return this.passport;
	}

	public void setPassport(Passport passport) {
		this.passport = passport;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "passport_group_id",nullable = false)
	public PassportGroup getPassportGroup() {
		return this.passportGroup;
	}

	public void setPassportGroup(PassportGroup passportGroup) {
		this.passportGroup = passportGroup;
	}

}
