package org.accretegb.modules.hibernate;


// Generated Jan 8, 2016 7:07:41 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PassportGroup generated by hbm2java
 */
@Entity
@Table(name = "passport_group", catalog = "agbv2")
public class PassportGroup implements java.io.Serializable {

	private Integer passportGroupId;
	private String groupName;
	private Set<PassportSet> passportSet = new HashSet(0);

	public PassportGroup() {
	}

	public PassportGroup(String groupName, Set<PassportSet> passportSet) {
		this.groupName = groupName;
		this.passportSet = passportSet;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "passport_group_id", unique = true, nullable = false)
	public Integer getPassportGroupId() {
		return this.passportGroupId;
	}

	public void setPassportGroupId(Integer passportGroupId) {
		this.passportGroupId = passportGroupId;
	}

	@Column(name = "group_name",nullable = false)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "passportGroup")
	public Set<PassportSet> getPassportSets() {
		return this.passportSet;
	}

	public void setPassportSets(Set<PassportSet> passportSet) {
		this.passportSet = passportSet;
	}

}
