package org.accretegb.modules.hibernate;
// Generated Jan 7, 2016 12:35:46 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Passport generated by hbm2java
 */
@Entity
@Table(name = "passport", catalog = "agbv2" )
public class Passport implements java.io.Serializable {

	private Integer passportId;
	private Source source;
	private CollectionInfo collectionInfo;
	private Classification classification;
	private Taxonomy taxonomy;
	private String accession_name;
	

	private String accession_identifier;
	private String pedigree;
	private String passportComments;
	private Set<PassportSet> passportSet = new HashSet(0);
	private Set<PassportSynonym> passportSynonyms = new HashSet(0);
	private Set<Stock> stocks = new HashSet(0);

	public Passport() {
	}

	public Passport(Source source, CollectionInfo collectionInfo, Classification classification,
			Taxonomy taxonomy, String accession_name, String accession_identifier, String pedigree,
			String passportComments, Set<PassportSet> passportSet, Set<PassportSynonym> passportSynonyms, Set<Stock> stocks) {
		this.source = source;
		this.collectionInfo = collectionInfo;
		this.classification = classification;
		this.taxonomy = taxonomy;
		this.accession_name = accession_name;
		this.accession_identifier = accession_identifier;
		this.pedigree = pedigree;
		this.passportComments = passportComments;
		this.passportSet = passportSet;
		this.passportSynonyms = passportSynonyms;
		this.stocks = stocks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "passport_id", unique = true, nullable = false)
	public Integer getPassportId() {
		return this.passportId;
	}

	public void setPassportId(Integer passportId) {
		this.passportId = passportId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "source_id")
	public Source getSource() {
		return this.source;
	}

	public void setSource(Source source) {
		this.source = source;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "collection_info_id")
	public CollectionInfo getCollectionInfo() {
		return this.collectionInfo;
	}

	public void setCollectionInfo(CollectionInfo collectionInfo) {
		this.collectionInfo = collectionInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "classification_id")
	public Classification getClassification() {
		return this.classification;
	}

	public void setClassification(Classification classification) {
		this.classification = classification;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "taxonomy_id")
	public Taxonomy getTaxonomy() {
		return this.taxonomy;
	}

	public void setTaxonomy(Taxonomy taxonomy) {
		this.taxonomy = taxonomy;
	}


	@Column(name = "accession_name",nullable = false)
	public String getAccession_name() {
		return accession_name;
	}

	public void setAccession_name(String accession_name) {
		this.accession_name = accession_name;
	}

	@Column(name = "accession_identifier",nullable = false)
	public String getAccession_identifier() {
		return accession_identifier;
	}

	public void setAccession_identifier(String accession_identifier) {
		this.accession_identifier = accession_identifier;
	}

	@Column(name = "pedigree", nullable = false)
	public String getPedigree() {
		return this.pedigree;
	}

	public void setPedigree(String pedigree) {
		this.pedigree = pedigree;
	}

	@Column(name = "passport_comments", length = 65535)
	public String getPassportComments() {
		return this.passportComments;
	}

	public void setPassportComments(String passportComments) {
		this.passportComments = passportComments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "passport")
	public Set<PassportSet> getPassportSets() {
		return this.passportSet;
	}

	public void setPassportSets(Set<PassportSet> passportSet) {
		this.passportSet = passportSet;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "passport")
	public Set<PassportSynonym> getPassportSynonyms() {
		return this.passportSynonyms;
	}

	public void setPassportSynonyms(Set<PassportSynonym> passportSynonyms) {
		this.passportSynonyms = passportSynonyms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "passport")
	public Set<Stock> getStocks() {
		return this.stocks;
	}

	public void setStocks(Set<Stock> stocks) {
		this.stocks = stocks;
	}

}
