package org.accretegb.modules.hibernate;

// default package
// Generated Jun 15, 2015 2:18:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PlantingGroup generated by hbm2java
 */
@Entity
@Table(name = "planting_group")
public class PlantingGroup implements java.io.Serializable {

	private Integer plantingGroupId;
	private int projectId;
	private String plantingGroupName;
	private String tableViewJson;
	private String tagGeneratorJson;

	public PlantingGroup() {
	}

	public PlantingGroup(int projectId, String plantingGroupName,
			String tableViewJson, String tagGeneratorJson) {
		this.projectId = projectId;
		this.plantingGroupName = plantingGroupName;
		this.tableViewJson = tableViewJson;
		this.tagGeneratorJson = tagGeneratorJson;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "planting_group_id", unique = true, nullable = false)
	public Integer getPlantingGroupId() {
		return this.plantingGroupId;
	}

	public void setPlantingGroupId(Integer plantingGroupId) {
		this.plantingGroupId = plantingGroupId;
	}

	@Column(name = "project_id", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "planting_group_name", nullable = false, length = 45)
	public String getPlantingGroupName() {
		return this.plantingGroupName;
	}

	public void setPlantingGroupName(String plantingGroupName) {
		this.plantingGroupName = plantingGroupName;
	}

	@Column(name = "tableView_json", nullable = true)
	public String getTableViewJson() {
		return this.tableViewJson;
	}

	public void setTableViewJson(String tableViewJson) {
		this.tableViewJson = tableViewJson;
	}

	@Column(name = "tagGenerator_json", nullable = true)
	public String getTagGeneratorJson() {
		return this.tagGeneratorJson;
	}

	public void setTagGeneratorJson(String tagGeneratorJson) {
		this.tagGeneratorJson = tagGeneratorJson;
	}

}
