package org.accretegb.modules.hibernate;
// Generated Jan 11, 2016 9:04:10 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "project", catalog = "agbv2")
public class Project implements java.io.Serializable {

	private Integer projectId;
	private Source source;
	private String projectName;
	private String projectObjective;
	private String personel;
	private String instituteName;
	private Set<Stock> stocks = new HashSet(0);

	public Project() {
	}

	public Project(Source source, String projectName, String projectObjective, String personel, String instituteName,
			Set<Stock> stocks) {
		this.source = source;
		this.projectName = projectName;
		this.projectObjective = projectObjective;
		this.personel = personel;
		this.instituteName = instituteName;
		this.stocks = stocks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "project_id", unique = true, nullable = false)
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "source_id")
	public Source getSource() {
		return this.source;
	}

	public void setSource(Source source) {
		this.source = source;
	}

	@Column(name = "project_name",nullable = false)
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Column(name = "project_objective")
	public String getProjectObjective() {
		return this.projectObjective;
	}

	public void setProjectObjective(String projectObjective) {
		this.projectObjective = projectObjective;
	}

	@Column(name = "personel")
	public String getPersonel() {
		return this.personel;
	}

	public void setPersonel(String personel) {
		this.personel = personel;
	}

	@Column(name = "institute_name")
	public String getInstituteName() {
		return this.instituteName;
	}

	public void setInstituteName(String instituteName) {
		this.instituteName = instituteName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	public Set<Stock> getStocks() {
		return this.stocks;
	}

	public void setStocks(Set<Stock> stocks) {
		this.stocks = stocks;
	}

}
