package org.accretegb.modules.hibernate;

// default package
// Generated Jun 15, 2015 2:18:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SamplingGroup generated by hbm2java
 */
@Entity
@Table(name = "sampling_group")
public class SamplingGroup implements java.io.Serializable {

	private Integer samplingGroupId;
	private int projectId;
	private String samplingGroupName;
	private String sampleSelectionJson;
	private String sampleSettingJson;

	public SamplingGroup() {
	}

	public SamplingGroup(int projectId, String samplingGroupName,
			String sampleSelectionJson, String sampleSettingJson) {
		this.projectId = projectId;
		this.samplingGroupName = samplingGroupName;
		this.sampleSelectionJson = sampleSelectionJson;
		this.sampleSettingJson = sampleSettingJson;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sampling_group_id", unique = true, nullable = false)
	public Integer getSamplingGroupId() {
		return this.samplingGroupId;
	}

	public void setSamplingGroupId(Integer samplingGroupId) {
		this.samplingGroupId = samplingGroupId;
	}

	@Column(name = "project_id", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "sampling_group_name", nullable = false, length = 45)
	public String getSamplingGroupName() {
		return this.samplingGroupName;
	}

	public void setSamplingGroupName(String samplingGroupName) {
		this.samplingGroupName = samplingGroupName;
	}

	@Column(name = "sample_selection_json", nullable = true)
	public String getSampleSelectionJson() {
		return this.sampleSelectionJson;
	}

	public void setSampleSelectionJson(String sampleSelectionJson) {
		this.sampleSelectionJson = sampleSelectionJson;
	}

	@Column(name = "sample_setting_json", nullable = true)
	public String getSampleSettingJson() {
		return this.sampleSettingJson;
	}

	public void setSampleSettingJson(String sampleSettingJson) {
		this.sampleSettingJson = sampleSettingJson;
	}

}
