package org.accretegb.modules.hibernate;
// Generated Jan 11, 2016 9:04:10 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Source generated by hbm2java
 */
@Entity
@Table(name = "source", catalog = "agbv2")
public class Source implements java.io.Serializable {

	private Integer sourceId;
	private Location location;
	private String personName;
	private String institute;
	private String department;
	private String streetAddress;
	private String phone;
	private String fax;
	private String email;
	private String url;
	private String sourceComments;
	private Set<CollectionInfo> collectionInfos = new HashSet(0);
	private Set<Project> projects = new HashSet(0);
	private Set<MeasurementValue> measurementValues = new HashSet(0);
	private Set<Passport> passports = new HashSet(0);

	public Source() {
	}

	
	public Source(Location location, String personName, String institute, String department, String streetAddress,
			String phone, String fax, String email, String url, String sourceComments, Set<CollectionInfo> collectionInfos,
			Set<Project> projects, Set<MeasurementValue> measurementValues, Set<Passport> passports) {
		this.location = location;
		this.personName = personName;
		this.institute = institute;
		this.department = department;
		this.streetAddress = streetAddress;
		this.phone = phone;
		this.fax = fax;
		this.email = email;
		this.url = url;
		this.sourceComments = sourceComments;
		this.collectionInfos = collectionInfos;
		this.projects = projects;
		this.measurementValues = measurementValues;
		this.passports = passports;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "source_id", unique = true, nullable = false)
	public Integer getSourceId() {
		return this.sourceId;
	}

	public void setSourceId(Integer sourceId) {
		this.sourceId = sourceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "location_id", nullable = false)
	public Location getLocation() {
		return this.location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

	@Column(name = "person_name",nullable = false)
	public String getPersonName() {
		return this.personName;
	}

	public void setPersonName(String personName) {
		this.personName = personName;
	}

	@Column(name = "institute")
	public String getInstitute() {
		return this.institute;
	}

	public void setInstitute(String institute) {
		this.institute = institute;
	}

	@Column(name = "department")
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "street_address")
	public String getStreetAddress() {
		return this.streetAddress;
	}

	public void setStreetAddress(String streetAddress) {
		this.streetAddress = streetAddress;
	}

	@Column(name = "phone")
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "fax")
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "source_comments", length = 65535)
	public String getSourceComments() {
		return this.sourceComments;
	}

	public void setSourceComments(String sourceComments) {
		this.sourceComments = sourceComments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "source")
	public Set<CollectionInfo> getCollectionInfos() {
		return this.collectionInfos;
	}

	public void setCollectionInfos(Set<CollectionInfo> collectionInfos) {
		this.collectionInfos = collectionInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "source")
	public Set<Project> getProject() {
		return this.projects;
	}

	public void setProject(Set<Project> projects) {
		this.projects = projects;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "source")
	public Set<MeasurementValue> getMeasurementValues() {
		return this.measurementValues;
	}

	public void setMeasurementValues(Set<MeasurementValue> measurementValues) {
		this.measurementValues = measurementValues;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "source")
	public Set<Passport> getPassports() {
		return this.passports;
	}

	public void setPassports(Set<Passport> passports) {
		this.passports = passports;
	}

}
