package org.accretegb.modules.hibernate;
// Generated Jan 7, 2016 12:35:46 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * StockGeneration generated by hbm2java
 */
@Entity
@Table(name = "stock_generation", catalog = "agbv2")
public class StockGeneration implements java.io.Serializable {

	private Integer stockGenerationId;
	private String generation;
	private String cycle;
	private String generationComments;
	private Set<Stock> stocks = new HashSet(0);

	public StockGeneration() {
	}

	public StockGeneration( String generation, String cycle,
			String generationComments, Set<Stock> stocks) {
		this.generation = generation;
		this.cycle = cycle;
		this.generationComments = generationComments;
		this.stocks = stocks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "stock_generation_id", unique = true, nullable = false)
	public Integer getStockGenerationId() {
		return this.stockGenerationId;
	}

	public void setStockGenerationId(Integer stockGenerationId) {
		this.stockGenerationId = stockGenerationId;
	}


	@Column(name = "generation",nullable = false)
	public String getGeneration() {
		return this.generation;
	}

	public void setGeneration(String generation) {
		this.generation = generation;
	}

	@Column(name = "cycle")
	public String getCycle() {
		return this.cycle;
	}

	public void setCycle(String cycle) {
		this.cycle = cycle;
	}

	@Column(name = "generation_comments", length = 65535)
	public String getGenerationComments() {
		return this.generationComments;
	}

	public void setGenerationComments(String generationComments) {
		this.generationComments = generationComments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stockGeneration")
	public Set<Stock> getStocks() {
		return this.stocks;
	}

	public void setStocks(Set<Stock> stocks) {
		this.stocks = stocks;
	}

}
