package org.accretegb.modules.hibernate;
// Generated Jan 12, 2016 9:32:23 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StockPacketContainer generated by hbm2java
 */
@Entity
@Table(name = "stock_packet_container", catalog = "agbv2")
public class StockPacketContainer implements java.io.Serializable {

	private Integer stockPacketContainerId;
	private ContainerLocation containerLocation;
	private String unit;
	private String stockPacketContainerComments;
	private Set<StockPacket> stockPackets = new HashSet(0);

	public StockPacketContainer() {
	}

	public StockPacketContainer(ContainerLocation containerLocation, String unit, String stockPacketContainerComments,
			Set<StockPacket> stockPackets) {
		this.containerLocation = containerLocation;
		this.unit = unit;
		this.stockPacketContainerComments = stockPacketContainerComments;
		this.stockPackets = stockPackets;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "stock_packet_container_id", unique = true, nullable = false)
	public Integer getStockPacketContainerId() {
		return this.stockPacketContainerId;
	}

	public void setStockPacketContainerId(Integer stockPacketContainerId) {
		this.stockPacketContainerId = stockPacketContainerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "container_location_id")
	public ContainerLocation getContainerLocation() {
		return this.containerLocation;
	}

	public void setContainerLocation(ContainerLocation containerLocation) {
		this.containerLocation = containerLocation;
	}

	@Column(name = "unit")
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Column(name = "stock_packet_container_comments", length = 65535)
	public String getStockPacketContainerComments() {
		return this.stockPacketContainerComments;
	}

	public void setStockPacketContainerComments(String stockPacketContainerComments) {
		this.stockPacketContainerComments = stockPacketContainerComments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stockPacketContainer")
	public Set<StockPacket> getStockPackets() {
		return this.stockPackets;
	}

	public void setStockPackets(Set<StockPacket> stockPackets) {
		this.stockPackets = stockPackets;
	}

}
