package org.accretegb.modules.hibernate;

// default package
// Generated May 27, 2015 9:54:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TokenRelation generated by hbm2java
 */
@Entity
@Table(name = "token_relation")
public class TokenRelation implements java.io.Serializable {

	private Integer tokenRelationId;
	private int userId;
	private int projectId;
	private Date expirationTime;

	public TokenRelation() {
	}

	public TokenRelation(int userId, int projectId, Date expirationTime) {
		this.userId = userId;
		this.projectId = projectId;
		this.expirationTime = expirationTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "token_relation_id", unique = true, nullable = false)
	public Integer getTokenRelationId() {
		return this.tokenRelationId;
	}

	public void setTokenRelationId(Integer tokenRelationId) {
		this.tokenRelationId = tokenRelationId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "project_id", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expiration_time", nullable = false, length = 19)
	public Date getExpirationTime() {
		return this.expirationTime;
	}

	public void setExpirationTime(Date expirationTime) {
		this.expirationTime = expirationTime;
	}

}
