package org.accretegb.modules.hibernate;
// Generated Jan 11, 2016 10:35:13 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "agbv2")
public class Users implements java.io.Serializable {

	private Integer usersId;
	private String username;
	private String password;
	private Date created;
	private Date modified;
	private String role;
	private String usersComments;
	private Set<FieldOwner> fieldOwners = new HashSet(0);

	public Users() {
	}

	public Users(String username, String password, Date created, Date modified) {
		this.username = username;
		this.password = password;
		this.created = created;
		this.modified = modified;
	}

	public Users(String username, String password, Date created, Date modified, String role, String usersComments,
			Set<FieldOwner> fieldOwners) {
		this.username = username;
		this.password = password;
		this.created = created;
		this.modified = modified;
		this.role = role;
		this.usersComments = usersComments;
		this.fieldOwners = fieldOwners;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "users_id", unique = true, nullable = false)
	public Integer getUsersId() {
		return this.usersId;
	}

	public void setUsersId(Integer usersId) {
		this.usersId = usersId;
	}

	@Column(name = "username", nullable = false, length = 100)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", nullable = false, length = 0)
	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	@Column(name = "role", length = 45)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "users_comments", length = 45)
	public String getUsersComments() {
		return this.usersComments;
	}

	public void setUsersComments(String usersComments) {
		this.usersComments = usersComments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<FieldOwner> getFieldOwners() {
		return this.fieldOwners;
	}

	public void setFieldOwners(Set<FieldOwner> fieldOwners) {
		this.fieldOwners = fieldOwners;
	}

}
